name: ventureit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  algolia: ^1.1.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  location: ^5.0.3
  preload_page_view: ^0.2.0
  riverpod_annotation: ^2.3.3
  routemaster: ^1.0.1
  url_launcher: ^6.2.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
